# Generated by Django 5.0.3 on 2024-03-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student'},
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='student',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
